# Generated by Django 5.1 on 2024-08-23 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_info', '0002_rename_marks_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='history',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='mark',
            name='maths',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='mark',
            name='pt',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='mark',
            name='science',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
