# Generated by Django 5.1 on 2024-08-23 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_info', '0003_alter_mark_history_alter_mark_maths_alter_mark_pt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='history',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mark',
            name='maths',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mark',
            name='pt',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mark',
            name='science',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
